# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VmLynMkfpQZ6oCutnRp34ko_Vd368K5w

AI Calculator
"""

pip install chatterbot

from chatterbot import ChatBot
Bot = ChatBot(name='AI Calculator',
              read_only=True,
              logic_adapters = ["chatterbot.logic.MathematicalEvaluation"],
              storage_adapter = "chatterbot.storage.SQLStorageAdapter")

print('/033c')
print("Hello, I am CalcAI your AI Calculator. How may I help you?")
while(True):
  user_input = input("me: ")
  if user_input.lower()=='quit':
    print("Exiting")
    break
  try:
    response = Bot.get_response(user_input)
    print("Calculator:",response)
  except:
    print("Calculator: Please enter valid input")

